# Generated by Django 3.0.5 on 2020-04-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
