# Generated by Django 3.0.5 on 2020-05-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200429_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='man',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
